CREATE TABLE product(
	id NUMBER PRIMARY KEY,
	name VARCHAR2(100) NOT NULL,
	maker VARCHAR2(100) NOT NULL,
	price NUMBER DEFAULT 0
)
INSERT INTO PRODUCT values(1,'불닭볶음면','삼양',1500);
INSERT INTO PRODUCT values(2,'진라면','오뚜기',1100);
INSERT INTO PRODUCT values(5,'참이슬','하이트진로',3000);

COMMIT

SELECT MIN(PRICE) FROM PRODUCT;
SELECT COUNT(*) FROM MEMBER;

SELECT name,price FROM product WHERE price>=1300 AND price<=2000 ORDER BY price ASC;