/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-11-11 22:16:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/KOSTA224/WAS/web-tomcat/webapps/semi-project-moco/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1636174144432L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container text-center\" style=\"padding: 0px 100px\">\r\n");
      out.write("	<div id=\"welcomText1\" class=\"animated1\" style=\"margin-top:180px; opacity:0;\">\r\n");
      out.write("		<h1 style=\"font-size:50px; font-weight: 900;\">W&nbsp;E&nbsp;L&nbsp;C&nbsp;O&nbsp;M&nbsp;E&nbsp;&nbsp;&nbsp;&nbsp;M&nbsp;O&nbsp;C&nbsp;O&nbsp;!</h1>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div style=\"margin-top: 50px;\">\r\n");
      out.write("		<img id=\"monitor\" class=\"animated2\" src=\"images/monitor.png\" style=\"width: 200px; margin-right: 50px; opacity: 0;\">\r\n");
      out.write("		<img id=\"code\" class=\"animated3\" src=\"images/code.png\" style=\"width: 130px; margin-left: 50px; opacity: 0;\">\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"welcomText2\" class=\"animated4\" style=\"margin-top:50px; opacity:0;\">\r\n");
      out.write("		<h3 style=\"font-size:30px; font-weight: 700;\">모코에서 질문하세요</h3>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"welcomText3\" class=\"animated4\" style=\"margin-top:30px; opacity:0;\">\r\n");
      out.write("		<h3 style=\"font-size:25px; font-weight: 700;\">코딩이 재미있어 질거에요😁</h3>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"con\" class=\"row row-cols-1 row-cols-md-2 animated1\" style=\"margin-top: 400px; opacity: 0; margin-bottom: 100px;\">\r\n");
      out.write("	     <div class=\"col mb-4\" id=\"javaBoard\">\r\n");
      out.write("	          <div class=\"card text-center boxShadow boardCard\">\r\n");
      out.write("	            <div class=\"card-header\">\r\n");
      out.write("	                 Java 질문 게시판\r\n");
      out.write("	            </div>\r\n");
      out.write("	               <div class=\"card-body\">\r\n");
      out.write("					<div class=\"lang-img-box align-middle\">\r\n");
      out.write("						<img src=\"images/java.png\" class=\"card-img-top lang-img\" alt=\"...\">\r\n");
      out.write("					</div>\r\n");
      out.write("	 				</div>\r\n");
      out.write("	          	</div>\r\n");
      out.write("	     </div>\r\n");
      out.write("	     <div class=\"col mb-4\" id=\"cBoard\">\r\n");
      out.write("	          <div class=\"card text-center boxShadow boardCard\">\r\n");
      out.write("	            <div class=\"card-header\">\r\n");
      out.write("	                 C 질문 게시판\r\n");
      out.write("	            </div>\r\n");
      out.write("	               <div class=\"card-body\">\r\n");
      out.write("					<div class=\"lang-img-box align-middle\">\r\n");
      out.write("						<img src=\"images/c.png\" class=\"card-img-top lang-img\" alt=\"...\">\r\n");
      out.write("					</div>\r\n");
      out.write("	 				</div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	     </div>\r\n");
      out.write("	     <div class=\"col mb-4\" id=\"pythonBoard\">\r\n");
      out.write("	          <div class=\"card text-center boxShadow boardCard\">\r\n");
      out.write("	            <div class=\"card-header\">\r\n");
      out.write("	                 Python 질문 게시판\r\n");
      out.write("	            </div>\r\n");
      out.write("	               <div class=\"card-body\">\r\n");
      out.write("					<div class=\"lang-img-box align-middle\">\r\n");
      out.write("						<img src=\"images/python.png\" class=\"card-img-top lang-img\" alt=\"...\">\r\n");
      out.write("					</div>\r\n");
      out.write("	 				</div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	     </div>\r\n");
      out.write("	     <div class=\"col mb-4\" id=\"etcBoard\">\r\n");
      out.write("	          <div class=\"card text-center boxShadow boardCard\">\r\n");
      out.write("	            <div class=\"card-header\">\r\n");
      out.write("	                 기타언어 질문 게시판\r\n");
      out.write("	            </div>\r\n");
      out.write("	               <div class=\"card-body\">\r\n");
      out.write("					<div class=\"lang-img-box align-middle\">\r\n");
      out.write("						<img src=\"images/etc.png\" class=\"card-img-top lang-img\" alt=\"...\">\r\n");
      out.write("					</div>\r\n");
      out.write("	 				</div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	     </div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
